In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [2]:
from IPython.display import Video, Image

# 介绍
Numpy提供多维数组对象以及一系列操作数组的函数，可以说其几乎是每一个Python科学计算软件的基础库

## import numpy as np

In [9]:
np.array?

In [19]:
a0 = np.array([1,2,3,4,5.2],dtype='int')

In [20]:
a0

array([1, 2, 3, 4, 5])

In [48]:
b0 =  np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

In [49]:
b0

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [102]:
b0.ndim

1

In [103]:
len(b0)

20

In [71]:
b0 =  np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],order='C')

In [77]:
b1 = b0.reshape(2,10,order='f')

In [78]:
b1

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [79]:
b1.strides

(8, 16)

In [88]:
a = np.random.rand(10, 3)
a

array([[0.98111553, 0.43989647, 0.73871995],
       [0.40115396, 0.28546901, 0.72319749],
       [0.22711099, 0.01786782, 0.68720185],
       [0.64491574, 0.69429206, 0.4759759 ],
       [0.00757222, 0.22084592, 0.30716348],
       [0.20593949, 0.59972045, 0.52439003],
       [0.97813765, 0.14621334, 0.06782522],
       [0.94499433, 0.43916891, 0.85364443],
       [0.79609295, 0.16661092, 0.7632867 ],
       [0.40032413, 0.71829997, 0.01368121]])

In [89]:
a.strides

(24, 8)

In [104]:
len(a)

10

In [92]:
b = a.transpose()

In [93]:
b.strides

(8, 24)

In [94]:
np.shares_memory(a,b)

True

In [108]:
a.shape

(10, 3)

In [99]:
a.strides

(24, 8)

In [101]:
np.ndim(a)

2

In [115]:
np.zeros((3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [116]:
np.ones((5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [117]:
np.full((10,10),8)

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [123]:
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [140]:
np.random.random((3,3))

array([[0.94757755, 0.83405848, 0.54057519],
       [0.97046489, 0.88238928, 0.83293052],
       [0.03005293, 0.58242712, 0.56329124]])

In [171]:
a = np.arange(3,11)

In [172]:
np.array(range(3,11))

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
np.reshape(a,(2,-1))

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [181]:
np.linspace?

In [182]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [183]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [185]:
a1 =np.arange(20).reshape(4,5,order='F')

In [186]:
a1

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [188]:
a1.shape 

(4, 5)

In [189]:
a1.strides

(8, 32)

In [190]:
a1 = np.array([[1,2],[3,4]])

In [191]:
a2 = np.array([[1,2],[3,4]])

In [192]:
a1 == a2

array([[ True,  True],
       [ True,  True]])

In [193]:
print(a1==a2)

[[ True  True]
 [ True  True]]


In [195]:
np.dot(a1,a2)

array([[ 7, 10],
       [15, 22]])

In [196]:
a1 +2

array([[3, 4],
       [5, 6]])

In [197]:
a1*3

array([[ 3,  6],
       [ 9, 12]])

In [199]:
a1.itemsize * a1.size

32

In [200]:
py_arr = [[1,2],[3,4]]

In [202]:
import sys
sys.getsizeof([1,2])

80

In [203]:
len(py_arr)

2

In [204]:
len(a1)

2

In [206]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [208]:
np.zeros((2,5),dtype='int') +1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [210]:
np.ones((2,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [211]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [213]:
b[1,1]=10

In [214]:
b

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [215]:
b1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [216]:
np.add(b,b1)

array([[ 2,  4,  6],
       [ 8, 15, 12],
       [14, 16, 18]])

In [223]:
np.amax(b)

10

In [224]:
b

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [225]:
np.amax(b,0)

array([ 7, 10,  9])

In [227]:
np.amax(b,1)

array([ 3, 10,  9])

In [228]:
def average_num():
    return sum([x*x for x in range(1,5)])

In [229]:
a =average_num()

In [230]:
a

30

In [231]:
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [232]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [234]:
a1 = np.arange(10).reshape(5,2)

In [235]:
a1 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [240]:
np.tril(a1.reshape(2,-1))

array([[0, 0, 0, 0, 0],
       [5, 6, 0, 0, 0]])

In [241]:
a1.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [242]:
np.triu(a1.reshape(2,-1))

array([[0, 1, 2, 3, 4],
       [0, 6, 7, 8, 9]])

In [244]:
a1 =np.full((10,10),1)

In [245]:
a1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [247]:
np.tril(a1)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [248]:
np.triu(a1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [258]:
np.triu(a1,-2)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

In [259]:
np.triu(a1,3)

array([[0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [260]:
np.random.rand(3,5)

array([[0.33736959, 0.36226301, 0.82656808, 0.52992291, 0.72234173],
       [0.2223887 , 0.67389842, 0.49469494, 0.19301628, 0.89023019],
       [0.82109879, 0.61730448, 0.62906802, 0.79496443, 0.95997562]])

In [261]:
np.random.random((3,5))

array([[0.59452486, 0.83885985, 0.0044196 , 0.09365155, 0.86084452],
       [0.06755429, 0.5426766 , 0.40690423, 0.62075121, 0.27481591],
       [0.92983283, 0.36195632, 0.64400906, 0.70473056, 0.21458207]])

In [ ]:
!head test.dat

In [ ]:
!wc test.dat

In [2]:
import numpy as np

In [3]:
np.random.rand(3,5)

array([[0.24476818, 0.7178365 , 0.32564285, 0.373822  , 0.93348976],
       [0.51664349, 0.06910211, 0.09607048, 0.81916424, 0.6893589 ],
       [0.06294167, 0.71912078, 0.9779178 , 0.03368157, 0.01517344]])

In [4]:
np.savetxt?

In [6]:
a =1e6

In [7]:
data = np.ran

1000000.0

In [21]:
a= list(range(10,20,2))

In [22]:
a

[10, 12, 14, 16, 18]

In [23]:
np.repeat(range(5),2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [28]:
a = np.arange(5) + np.arange(0,60,10).reshape(6,-1)

In [29]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [32]:
print(a[:,1:3])

[[ 1  2]
 [11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]


In [33]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [35]:
a[a>1] =10

In [36]:
a

array([[ 0,  1, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [37]:
a = np.arange(5) + np.arange(0,60,10).reshape(6,-1)

In [38]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [39]:
np.where(a>1)

(array([0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4, 5, 5, 5, 5, 5]),
 array([2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,
        4, 0, 1, 2, 3, 4]))

In [41]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [43]:
b =np.copy(a)

In [44]:
b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [45]:
b.T

array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54]])

In [47]:
b.T.T

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [50]:
b

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [77]:
np.max(b,axis=-2)

array([50, 51, 52, 53, 54])

In [63]:
np.max?

In [2]:
from IPython.display import Video
Video("game-of-life.mp4")

ValueError: To embed videos, you must pass embed=True (this may make your notebook files huge)
Consider passing Video(url='...')

In [3]:
import numpy as np


In [6]:
a = np.full((2,5),3)

In [7]:
a

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
b = np.ravel(a)

In [11]:
b

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [16]:
c = np.transpose(a)

In [17]:
c

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [18]:
d = a.T

In [19]:
d

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [22]:
import time

In [37]:
time.clock()

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.


2.853816

In [27]:
a

2.682436

In [45]:
a =np.linspace(0,10)

In [47]:
np.linspace?

$$  P(A \mid B) = \frac{P(B \mid A)P(A)}{P(B)} $$

$$ a \approx b $$

In [49]:
a

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [50]:
np.savetxt('abc.txt',a)

In [52]:
!ls

abc.txt        lesson01.ipynb


In [56]:
np.loadtxt('abc.txt',delimiter=',')

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])